// GENERATED by tools/otio_codegen.R -- DO NOT EDIT.
// Trivial scalar getters over wrapped OTIO objects. Each was validated
// against the OTIO headers (see tools/otio_introspect.R) before emission.
// Regenerate with: r -e 'source("tools/otio_codegen.R"); otio_generate()'

#include "otio_common.h"
#include <opentimelineio/timeline.h>
#include <opentimelineio/track.h>
#include <opentimelineio/clip.h>
#include <opentimelineio/externalReference.h>
#include <opentimelineio/serializableObjectWithMetadata.h>

// [[Rcpp::export]]
std::string otio_get_timeline_name(SEXP p) {
    return unwrap_otio<otio::Timeline>(p)->name();
}

// [[Rcpp::export]]
std::string otio_get_track_name(SEXP p) {
    return unwrap_otio<otio::Track>(p)->name();
}

// [[Rcpp::export]]
std::string otio_get_track_kind(SEXP p) {
    return unwrap_otio<otio::Track>(p)->kind();
}

// [[Rcpp::export]]
std::string otio_get_clip_name(SEXP p) {
    return unwrap_otio<otio::Clip>(p)->name();
}

// [[Rcpp::export]]
std::string otio_get_clip_active_media_reference_key(SEXP p) {
    return unwrap_otio<otio::Clip>(p)->active_media_reference_key();
}

// [[Rcpp::export]]
std::string otio_get_externalreference_target_url(SEXP p) {
    return unwrap_otio<otio::ExternalReference>(p)->target_url();
}

