// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// otio_rt_create
SEXP otio_rt_create(double value, double rate);
RcppExport SEXP _nle_api_otio_rt_create(SEXP valueSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_create(value, rate));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_value
double otio_rt_value(SEXP ptr);
RcppExport SEXP _nle_api_otio_rt_value(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_value(ptr));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_rate
double otio_rt_rate(SEXP ptr);
RcppExport SEXP _nle_api_otio_rt_rate(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_rate(ptr));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_to_seconds
double otio_rt_to_seconds(SEXP ptr);
RcppExport SEXP _nle_api_otio_rt_to_seconds(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_to_seconds(ptr));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_to_frames
int otio_rt_to_frames(SEXP ptr, double rate);
RcppExport SEXP _nle_api_otio_rt_to_frames(SEXP ptrSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_to_frames(ptr, rate));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_rescaled_to
SEXP otio_rt_rescaled_to(SEXP ptr, double new_rate);
RcppExport SEXP _nle_api_otio_rt_rescaled_to(SEXP ptrSEXP, SEXP new_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type new_rate(new_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_rescaled_to(ptr, new_rate));
    return rcpp_result_gen;
END_RCPP
}
// otio_rt_to_timecode
std::string otio_rt_to_timecode(SEXP ptr, double rate);
RcppExport SEXP _nle_api_otio_rt_to_timecode(SEXP ptrSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(otio_rt_to_timecode(ptr, rate));
    return rcpp_result_gen;
END_RCPP
}
// otio_opentime_version
std::string otio_opentime_version();
RcppExport SEXP _nle_api_otio_opentime_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(otio_opentime_version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nle_api_otio_rt_create", (DL_FUNC) &_nle_api_otio_rt_create, 2},
    {"_nle_api_otio_rt_value", (DL_FUNC) &_nle_api_otio_rt_value, 1},
    {"_nle_api_otio_rt_rate", (DL_FUNC) &_nle_api_otio_rt_rate, 1},
    {"_nle_api_otio_rt_to_seconds", (DL_FUNC) &_nle_api_otio_rt_to_seconds, 1},
    {"_nle_api_otio_rt_to_frames", (DL_FUNC) &_nle_api_otio_rt_to_frames, 2},
    {"_nle_api_otio_rt_rescaled_to", (DL_FUNC) &_nle_api_otio_rt_rescaled_to, 2},
    {"_nle_api_otio_rt_to_timecode", (DL_FUNC) &_nle_api_otio_rt_to_timecode, 2},
    {"_nle_api_otio_opentime_version", (DL_FUNC) &_nle_api_otio_opentime_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_nle_api(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
