# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

otio_timeline_clips_df <- function(tl) {
    .Call(`_nle_api_otio_timeline_clips_df`, tl)
}

otio_build_timeline <- function(name, fps_num, fps_den, canvas_w, canvas_h, sample_rate, track_ids, track_kinds, clip_track, clip_id, clip_asset, clip_tl_in, clip_tl_out, clip_src_in, clip_rate, clip_speed, prev) {
    .Call(`_nle_api_otio_build_timeline`, name, fps_num, fps_den, canvas_w, canvas_h, sample_rate, track_ids, track_kinds, clip_track, clip_id, clip_asset, clip_tl_in, clip_tl_out, clip_src_in, clip_rate, clip_speed, prev)
}

otio_timeline_config <- function(tl) {
    .Call(`_nle_api_otio_timeline_config`, tl)
}

otio_timeline_clone <- function(tl) {
    .Call(`_nle_api_otio_timeline_clone`, tl)
}

otio_clip_effect_add <- function(tl, clip_id, effect_name, params, enabled) {
    .Call(`_nle_api_otio_clip_effect_add`, tl, clip_id, effect_name, params, enabled)
}

otio_clip_effects_df <- function(tl, clip_id) {
    .Call(`_nle_api_otio_clip_effects_df`, tl, clip_id)
}

otio_clip_effect_params <- function(tl, clip_id, index) {
    .Call(`_nle_api_otio_clip_effect_params`, tl, clip_id, index)
}

otio_clip_effect_remove <- function(tl, clip_id, index) {
    .Call(`_nle_api_otio_clip_effect_remove`, tl, clip_id, index)
}

otio_timeline_create <- function(name) {
    .Call(`_nle_api_otio_timeline_create`, name)
}

otio_externalreference_create <- function(name) {
    .Call(`_nle_api_otio_externalreference_create`, name)
}

otio_get_timeline_name <- function(p) {
    .Call(`_nle_api_otio_get_timeline_name`, p)
}

otio_get_track_name <- function(p) {
    .Call(`_nle_api_otio_get_track_name`, p)
}

otio_get_track_kind <- function(p) {
    .Call(`_nle_api_otio_get_track_kind`, p)
}

otio_get_clip_name <- function(p) {
    .Call(`_nle_api_otio_get_clip_name`, p)
}

otio_get_clip_active_media_reference_key <- function(p) {
    .Call(`_nle_api_otio_get_clip_active_media_reference_key`, p)
}

otio_get_externalreference_target_url <- function(p) {
    .Call(`_nle_api_otio_get_externalreference_target_url`, p)
}

otio_set_timeline_name <- function(p, v) {
    invisible(.Call(`_nle_api_otio_set_timeline_name`, p, v))
}

otio_set_track_name <- function(p, v) {
    invisible(.Call(`_nle_api_otio_set_track_name`, p, v))
}

otio_set_track_kind <- function(p, v) {
    invisible(.Call(`_nle_api_otio_set_track_kind`, p, v))
}

otio_set_externalreference_target_url <- function(p, v) {
    invisible(.Call(`_nle_api_otio_set_externalreference_target_url`, p, v))
}

otio_track_create <- function(name, kind) {
    .Call(`_nle_api_otio_track_create`, name, kind)
}

otio_clip_create <- function(name, target_url, start_value, start_rate, dur_value, dur_rate) {
    .Call(`_nle_api_otio_clip_create`, name, target_url, start_value, start_rate, dur_value, dur_rate)
}

otio_timeline_add_track <- function(tl, track) {
    .Call(`_nle_api_otio_timeline_add_track`, tl, track)
}

otio_track_add_clip <- function(track, clip) {
    .Call(`_nle_api_otio_track_add_clip`, track, clip)
}

otio_track_remove_clip <- function(track, index) {
    .Call(`_nle_api_otio_track_remove_clip`, track, index)
}

otio_timeline_to_json <- function(tl) {
    .Call(`_nle_api_otio_timeline_to_json`, tl)
}

otio_timeline_from_json <- function(json) {
    .Call(`_nle_api_otio_timeline_from_json`, json)
}

otio_timeline_tracks_df <- function(tl) {
    .Call(`_nle_api_otio_timeline_tracks_df`, tl)
}

otio_track_clips_df <- function(track) {
    .Call(`_nle_api_otio_track_clips_df`, track)
}

otio_rt_create <- function(value, rate) {
    .Call(`_nle_api_otio_rt_create`, value, rate)
}

otio_rt_value <- function(ptr) {
    .Call(`_nle_api_otio_rt_value`, ptr)
}

otio_rt_rate <- function(ptr) {
    .Call(`_nle_api_otio_rt_rate`, ptr)
}

otio_rt_to_seconds <- function(ptr) {
    .Call(`_nle_api_otio_rt_to_seconds`, ptr)
}

otio_rt_to_frames <- function(ptr, rate) {
    .Call(`_nle_api_otio_rt_to_frames`, ptr, rate)
}

otio_rt_rescaled_to <- function(ptr, new_rate) {
    .Call(`_nle_api_otio_rt_rescaled_to`, ptr, new_rate)
}

otio_rt_to_timecode <- function(ptr, rate) {
    .Call(`_nle_api_otio_rt_to_timecode`, ptr, rate)
}

otio_opentime_version <- function() {
    .Call(`_nle_api_otio_opentime_version`)
}

