# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

otio_rt_create <- function(value, rate) {
    .Call('_nle_api_otio_rt_create', PACKAGE = 'nle.api', value, rate)
}

otio_rt_value <- function(ptr) {
    .Call('_nle_api_otio_rt_value', PACKAGE = 'nle.api', ptr)
}

otio_rt_rate <- function(ptr) {
    .Call('_nle_api_otio_rt_rate', PACKAGE = 'nle.api', ptr)
}

otio_rt_to_seconds <- function(ptr) {
    .Call('_nle_api_otio_rt_to_seconds', PACKAGE = 'nle.api', ptr)
}

otio_rt_to_frames <- function(ptr, rate) {
    .Call('_nle_api_otio_rt_to_frames', PACKAGE = 'nle.api', ptr, rate)
}

otio_rt_rescaled_to <- function(ptr, new_rate) {
    .Call('_nle_api_otio_rt_rescaled_to', PACKAGE = 'nle.api', ptr, new_rate)
}

otio_rt_to_timecode <- function(ptr, rate) {
    .Call('_nle_api_otio_rt_to_timecode', PACKAGE = 'nle.api', ptr, rate)
}

otio_opentime_version <- function() {
    .Call('_nle_api_otio_opentime_version', PACKAGE = 'nle.api')
}

